### ISSUE TITLE
Panel not closing on lost focus (blur)

### ISSUE THREAD

**Issue by imdadturi** [gmerabishvili/angular-ng-autocomplete#113] opened 2020-10-19 07:53 UTC
Hello,
I have multiple ng-autocomplete and when I open panel go to another open another, they remain opened until you select something. It should close when Focus is lost or blur event should be provided to control that behavior.

Please consider the issue

**Comment by gmerabishvili** [comment] 2020-12-27 18:52
@imdadturi What version of autocomplete are you using? The issue is fixed on latest one. Thank you.

**Closed by gmerabishvili** 2020-12-27 18:52 UTC
